#ifndef VANARIZE_COMPILER_TOKEN_H
#define VANARIZE_COMPILER_TOKEN_H

#include <stddef.h>

typedef enum {
    // Single-character tokens
    TOKEN_LEFT_PAREN, TOKEN_RIGHT_PAREN,
    TOKEN_LEFT_BRACE, TOKEN_RIGHT_BRACE,
    TOKEN_COMMA, TOKEN_DOT, TOKEN_MINUS, TOKEN_PLUS,
    TOKEN_SEMICOLON, TOKEN_SLASH, TOKEN_STAR,
    TOKEN_COLON, TOKEN_DOUBLE_COLON, // ::

    // One or two character tokens
    TOKEN_BANG, TOKEN_BANG_EQUAL,
    TOKEN_EQUAL, TOKEN_EQUAL_EQUAL,
    TOKEN_GREATER, TOKEN_GREATER_EQUAL,
    TOKEN_LESS, TOKEN_LESS_EQUAL,

    // Literals
    TOKEN_IDENTIFIER, TOKEN_STRING, TOKEN_NUMBER,

    // Keywords
    TOKEN_AND, TOKEN_CLASS, TOKEN_ELSE, TOKEN_FALSE,
    TOKEN_FOR, TOKEN_FUNCTION, TOKEN_IF, TOKEN_NIL,
    TOKEN_OR, TOKEN_PRINT, TOKEN_RETURN, TOKEN_SUPER,
    TOKEN_THIS, TOKEN_TRUE,
    TOKEN_STRUCT, TOKEN_IMPORT, TOKEN_ASYNC, TOKEN_AWAIT,
    
    // Types (Java Primitives)
    TOKEN_TYPE_BYTE, TOKEN_TYPE_SHORT, TOKEN_TYPE_INT, TOKEN_TYPE_LONG,
    TOKEN_TYPE_FLOAT, TOKEN_TYPE_DOUBLE, TOKEN_TYPE_CHAR, TOKEN_TYPE_BOOLEAN,
    TOKEN_TYPE_STRING, // Java Object Type as Primal String type
    TOKEN_TYPE_VOID, // Void return type

    TOKEN_ERROR, TOKEN_EOF
} TokenType;

typedef struct {
    TokenType type;
    const char* start;
    int length;
    int line;
} Token;

#endif // VANARIZE_COMPILER_TOKEN_H
